In [ ]:
from math import sqrt
sqrt(4)

2.0

In [ ]:
scores = [12,4,8,10]
print(scores*2)

[12, 4, 8, 10, 12, 4, 8, 10]


In [ ]:
import numpy as np
scores = np.array(scores)
print(scores*2)

[24  8 16 20]


In [ ]:
arr = np.array([1,2,3,4,5])
print(arr + 2)


[3 4 5 6 7]


In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
# np.arange(start , stop, step)
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
np.linspace(0,1,5)   # (start, stop, count)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.linspace(0,100,6)

array([  0.,  20.,  40.,  60.,  80., 100.])

In [ ]:
scores = np.array([90,85,78,92,88])
scores.shape

(5,)

In [ ]:
scores.ndim

1

In [ ]:
scores.dtype

dtype('int64')

In [ ]:
arr = np.array([10,20,30]) #1d array  shape = (3,)


In [ ]:
arr2 = np.array([
    [90,85,78,92],
    [70,88,95,60],
    [82,89,24,54]
])

In [ ]:
arr2.shape

(3, 4)

In [ ]:
arr2.ndim

2

In [ ]:
arr = np.array([
    [[1,2,3,4],
     [1,2,3,4]],
      [[1,2,3,4],
       [1,2,3,4]],
        [[1,2,3,4],
         [1,2,3,4]]
    ])
arr2 = np.array([
    [90,85,78,92],
    [70,88,95,60],
    [82,89,24,54]
])

In [ ]:
arr.shape

(3, 2, 4)

# indexing and slicing

In [ ]:
arr = np.array([10,20,30,40])
print(arr[0])

10


In [ ]:
print(arr[-1])

40


In [ ]:
arr2 = np.array([
    [90,85,78,92],
    [70,88,95,60],
    [82,89,24,54]
])

print(arr2[1][1])

88


In [ ]:
print(arr2[2][3])

54


In [ ]:
arr2 = np.array([
    [[1,2],[3,4],[5,6]],
    [[7,8],[9,10],[11,12]],
    [[13,14],[15,16],[17,18]]
])

print(arr2[2][1][1])
print(arr2[1][2][1])

16
12


In [ ]:
arr = np.array([10,20,30,40])
print(arr[1:3])

[20 30]


In [ ]:
arr2 = np.array([
    [90,85,78,92],
    [70,88,95,60],
    [82,89,24,54]
])

print(arr2[0:2,1:3])


[[85 78]
 [88 95]]


In [ ]:
arr2[1,1:3]

array([88, 95])

In [ ]:
arr2[:,1]

array([85, 88, 89])

In [ ]:
arr2[:, :]

array([[90, 85, 78, 92],
       [70, 88, 95, 60],
       [82, 89, 24, 54]])

# boolean indexing

In [ ]:
scores= np.array([55,90,43,81,89])
passed = scores[scores>=60]
print(passed)

[90 81 89]


In [ ]:
[scores>=60]

[array([False,  True, False,  True,  True])]

In [ ]:
ages[ages>30]

# array math

In [ ]:
a = np.array([1,2,3])
b = np.array([10,20,30])
a + b

array([11, 22, 33])

In [ ]:
a*b

array([10, 40, 90])

In [ ]:
a +5

array([6, 7, 8])

In [ ]:
grades = np.array([
    [90,85,76,67],
    [70,88,77,90]
])

bonus =np.array([2,2,0,4])

grades+bonus

array([[92, 87, 76, 71],
       [72, 90, 77, 94]])

In [ ]:
# scores = [1,2,3,4]
# for s in scores:
#   s+=3
#   print(s)

4
5
6
7


In [ ]:
scores= np.array([55,90,43,81,89])
print(scores.sum())

358


In [ ]:
print(scores.mean())

71.6


In [ ]:
print(scores.max())
print(scores.min())

90
43


In [ ]:
print(scores.std())

19.095549219648017


In [ ]:
grades = np.array([
    [90,85,76,67],
    [70,88,77,90]
])

print(grades.sum())
print(grades.sum(axis=1))
print(grades.sum(axis=0))

643
[318 325]
[160 173 153 157]


In [ ]:
grades = np.array([
    [90,85,76,67],
    [70,88,77,90]
])
print(grades.mean())
print(grades.mean(axis=1))
print(grades.mean(axis=0))

80.375
[79.5  81.25]
[80.  86.5 76.5 78.5]


# reshape

In [ ]:
nums = np.arange(1,13)

In [ ]:
print(nums)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
grid = nums.reshape(3,4)

In [ ]:
print(grid)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
grid = nums.reshape(2,6)
grid

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
grid = nums.reshape(3,3)
grid

ValueError: cannot reshape array of size 12 into shape (3,3)

# random

In [ ]:
np.random.seed(23)
dice = np.random.randint(1,7,size =5)
print(dice)

[4 1 2 1 6]


# **sorting**

In [ ]:
scores= np.array([55,90,43,81,89])
np.sort(scores)

array([43, 55, 81, 89, 90])

In [ ]:
print(scores.argmax())

1
